### ISSUE TITLE
is alfresco BM 2.7 is compatible with alfresco 4.1.4  ? While running data load test against alf 4.1.4 with BM 2.7 it is creating blank site and suddenly stopping the test ang giving below error ?

### ISSUE THREAD

**Issue by Yogesh102** [AlfrescoBenchmark/alfresco-benchmark#126]
2017-06-09T14:37:28.750-04:00] Event processing exception; no further events will be published. 
 org.springframework.social.alfresco.connect.exception.AlfrescoException: 409 response status Conflict response body <html><head><title>Apache Tomcat/6.0.35 - Error report</title><style></style> </head><body><h1>HTTP Status 409 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request could not be completed due to a conflict with the current state of the resource ().</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.35</h3></body></html>
 at org.springframework.social.alfresco.api.impl.AbstractAlfrescoTemplate$1.handleError(AbstractAlfrescoTemplate.java:626)
 at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:588)
 at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
 at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:510)
 at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:340)
 at org.springframework.social.alfresco.api.impl.AbstractAlfrescoTemplate.createSite(AbstractAlfrescoTemplate.java:1928)
 at org.alfresco.bm.dataload.CreateSite.processEvent(CreateSite.java:109)
 at org.alfresco.bm.event.AbstractEventProcessor.processEvent(AbstractEventProcessor.java:278)
 at org.alfresco.bm.event.EventWork.run(EventWork.java:108)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by derekhulley** [comment]
The site creation APIs have moved on since **4.1.N**.  I would suggest that you always use the latest Alfresco and the latest load drivers.
