### ISSUE TITLE
Hardcoded FTP site in JUnit test fails if server is down

### ISSUE THREAD

**Issue by kamaldeepsaini** [AlfrescoBenchmark/alfresco-benchmark#86]
Hi I was building the project and got below error, It seems like ftp location is down i.e ftp.mirrorservice.org. 

Please check and confirm.

org.alfresco.bm.file.FileDataServiceTest  Time elapsed: 69.937 sec  <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ftpTestFileService' defined in class path resource [test-MongoFileDataTest-context.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: FTP file listing failed: FtpTestFileService [ftpHost=ftp.mirrorservice.org, ftpPort=21, ftpUsername=anonymous, ftpPassword=*****, ftpPath=/sites/www.linuxfromscratch.org/images]
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:182)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
	at org.alfresco.bm.file.FtpTestFileService.getFTPClient(FtpTestFileService.java:103)
	at org.alfresco.bm.file.FtpTestFileService.listRemoteFiles(FtpTestFileService.java:149)
	at org.alfresco.bm.file.AbstractTestFileService.indexFileData(AbstractTestFileService.java:199)
	at org.alfresco.bm.file.AbstractTestFileService.afterPropertiesSet(AbstractTestFileService.java:63)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.alfresco.bm.file.FileDataServiceTest.setUp(FileDataServiceTest.java:92)

**Comment by fkbecker** [comment]
Hi,

I also build the project and at least now everything works as it should. 
The FTP test site is hard-coded in the test (FileDataServiceTest), this should be altered to get it from the properties file.

Cheers, Frank

**Comment by kamaldeepsaini** [comment]
Hi,

For now it is working for me as well. 

Thanks,
Kamal

**Comment by fkbecker** [comment]
Fixed with 2.1.1
