### ISSUE TITLE
MongoDB 3.2 not compatible with Benchmark Framework 

### ISSUE THREAD

**Issue by HansDeBal** [AlfrescoBenchmark/alfresco-benchmark#96]
I cloned this project and installed mongodb 3.2. When following the instructions in martin's document I encounter the following issue:
* when starting the mgmt-server everything works fine.
* when I try to start the first Test Driver, I get the following mongo-error:

```
2016-01-05 09:37:22,198 [localhost-startStop-1] [INFO ] [alfresco.mongo.MongoClientFactory: 124] New MongoDB client created using URL: mongodb://localhost/?connectTimeoutMS=5000&socketTimeoutMS=60000&safe=true
2016-01-05 09:37:22,276 [localhost-startStop-1] [ERROR] [web.context.ContextLoader: 331] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'api.v1.tests' defined in class path resource [config/spring/app-context.xml]: Cannot resolve reference to bean 'logService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logService' defined in class path resource [config/spring/app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.bm.log.MongoLogService]: Constructor threw exception; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "collection already exists" , "code" : 48}
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:336)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:646)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4937)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logService' defined in class path resource [config/spring/app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.bm.log.MongoLogService]: Constructor threw exception; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "collection already exists" , "code" : 48}
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:278)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	... 26 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.bm.log.MongoLogService]: Constructor threw exception; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "collection already exists" , "code" : 48}
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:164)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:125)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:270)
	... 35 more
Caused by: com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "collection already exists" , "code" : 48}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
	at com.mongodb.DB.createCollection(DB.java:202)
	at org.alfresco.bm.log.MongoLogService.<init>(MongoLogService.java:88)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 37 more
```

When I remove all collections in the database, first start the test driver and then the mgmt-server, the same error occurs but then in the mgmt-server log

**Comment by HansDeBal** [comment]
Forgot to mention: have the same problem for 2.1.1 and 2.1.2-SNAPSHOT

**Comment by fkbecker** [comment]
Did you set the -Dmongo.config.host=<mongoIP> on both driver and server Tomcat? Because this seems to be a Mongo connection issue.
 
Please also try for example "RoboMongo" to connect the mongo host to make sure it's running fine. Please report if it works or you still need help, thanks.

**Comment by HansDeBal** [comment]
Yes, i used the exact commands as explained in the documentation:
alfresco-benchmark/server$ mvn tomcat7:run -Dmongo.config.host=localhost
and
alfresco-benchmark/sample$ mvn tomcat7:run -Dmongo.config.host=localhost

I installed mongo locally

Tried robomongo and can connect to my local mongo-instance.

When I stop the test driver and the mgmt-server, and only start the mgmt-server, I get the same error. When I delete the bm20-config and bm20-log database and then start the first server, it runs fine. Once the databases are created (by the first server that starts), the problem occurs with every server I start (until I remove the databases again).

**Comment by fkbecker** [comment]
I just validated on Mac OS X 10.9 with MongoDB 3.0.8 installed on localhost (created /data/db and set to 777 with chmod) - downloaded the sources of 2.1.2-SNAPSHOT and first run mvn clean:install, than started both server and driver - I repeated this more than once and it still works fine. Note: I use Java 1.8 for the latest SNAPSHOT is Java 8 instead 7 now. My Maven version is 3.3.9.  

So there might be an issue in your local environment. What OS do you use? 
Can you maybe try to go back to MongoDB 3.0.8? I will asap try with MongoDB 3.2 as well.

**Comment by fkbecker** [comment]
With MongoDB 3.2 installed on Ubuntu I have the same problems. 
please use MongoDB 3.0.x as long as this issue isn't fixed. Thanks!

**Comment by HansDeBal** [comment]
I will do that! thanks Frank!

**Comment by fkbecker** [comment]
In the meanwhile I upgraded the server to MongoDB Java driver version 3.2 - but there seems to be bugs in the driver, that I reported to the MongoDB team. I will continue with tests vs. older versions of the DB and the latest driver, but for now MongoDB 3.2 is not supported.

**Comment by fkbecker** [comment]
Fixed in 2.1.2-SNAPSHOT, but still more testing required. 
Will be done in overall testing with next release, for there are more updates (AngularJS, Bootstrap, JQuery) that needs to be tested.

**Comment by fkbecker** [comment]
Fixed with 2.1.2

**Comment by fjwu121** [comment]
as of 2018 Feb, if you follow Alfresco Benchmark 'Getting Started Writing your own tests' - Source Code, you will get the same error. After analyzing the pom.xml file, it is clear it uses older version. For example, it is missing
    <parent>
        <groupId>org.alfresco</groupId>
        <artifactId>alfresco-benchmark</artifactId>
        <version>2.2.1-SNAPSHOT</version>
    </parent>
After manually correcting pom.xml,  I fixed this error. The Mongodb will have bm-21.* rather than bm-20.* databases.

**Comment by derekhulley** [comment]
Thanks for the update.
Perhaps you could submit a README.md that contains better instructions than that document.

**Comment by fkbecker** [comment]
@fjwu121 yes, unfortunately the documentation is a bit outdated.
